services:
  - type: web
    name: mondelez-target-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-production-secret-key
      - key: DEBUG
        value: False
